import {
  Product,
  Customer,
  SaleTransaction,
  AIPredictionOverview,
  SalesForecastPoint,
  DemandForecastItem,
  BundleRecommendation,
} from "../types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    sku: "TXT-SILK-001",
    name: "Pure Banarasi Zari Brocade Saree",
    category: "Silk Sarees",
    fabricType: "Katan Silk",
    weaveType: "Jacquard Weave",
    gsm: 120,
    color: "Royal Crimson Red",
    unitPrice: 8500,
    mrp: 14500,
    stockQuantity: 45,
    unitOfMeasure: "Pieces",
    reorderLevel: 15,
    supplierName: "Varanasi Heritage Weavers",
    status: "In Stock",
    createdAt: "2026-01-10",
  },
  {
    id: "prod-002",
    sku: "TXT-COT-002",
    name: "Chanderi Handloom Cotton Fabric",
    category: "Cotton Fabrics",
    fabricType: "Chanderi Cotton",
    weaveType: "Plain Weave",
    gsm: 75,
    color: "Pastel Mint Green",
    unitPrice: 280,
    mrp: 450,
    stockQuantity: 12,
    unitOfMeasure: "Meters",
    reorderLevel: 50,
    supplierName: "Chanderi Craft Co-op",
    status: "Low Stock",
    createdAt: "2026-02-01",
  },
  {
    id: "prod-003",
    sku: "TXT-DRS-003",
    name: "Embroidered Georgette Anarkali Material",
    category: "Dress Material",
    fabricType: "Faux Georgette",
    weaveType: "Chiffon Weave",
    gsm: 90,
    color: "Deep Sapphire Blue",
    unitPrice: 1650,
    mrp: 2890,
    stockQuantity: 85,
    unitOfMeasure: "Pieces",
    reorderLevel: 20,
    supplierName: "Surat Tex Fabrics",
    status: "In Stock",
    createdAt: "2026-01-25",
  },
  {
    id: "prod-004",
    sku: "TXT-SUIT-004",
    name: "Super 120s Italian Wool Blend Suiting",
    category: "Suiting & Shirting",
    fabricType: "Wool Rayon Blend",
    weaveType: "Twill Weave",
    gsm: 240,
    color: "Charcoal Grey",
    unitPrice: 620,
    mrp: 990,
    stockQuantity: 8,
    unitOfMeasure: "Meters",
    reorderLevel: 30,
    supplierName: "Raymond Mills Distributor",
    status: "Low Stock",
    createdAt: "2026-02-14",
  },
  {
    id: "prod-005",
    sku: "TXT-LIN-005",
    name: "100% Pure Organic Linen Fabric",
    category: "Linen Collection",
    fabricType: "Flax Linen",
    weaveType: "Basket Weave",
    gsm: 160,
    color: "Natural Ecru Beige",
    unitPrice: 890,
    mrp: 1400,
    stockQuantity: 120,
    unitOfMeasure: "Meters",
    reorderLevel: 25,
    supplierName: "Bhagalpur Linen Mills",
    status: "In Stock",
    createdAt: "2026-03-02",
  },
  {
    id: "prod-006",
    sku: "TXT-LEH-006",
    name: "Heavy Velvet Zardozi Bridal Lehenga Fabric",
    category: "Designer Lehengas",
    fabricType: "Micro Velvet 9000",
    weaveType: "Velvet Cut Weave",
    gsm: 310,
    color: "Maroon Rose",
    unitPrice: 18500,
    mrp: 29900,
    stockQuantity: 3,
    unitOfMeasure: "Pieces",
    reorderLevel: 5,
    supplierName: "Jaipur Artisan Guild",
    status: "Low Stock",
    createdAt: "2026-03-10",
  },
  {
    id: "prod-007",
    sku: "TXT-KUR-007",
    name: "Jaipuri Block Print Kurti Fabric",
    category: "Cotton Fabrics",
    fabricType: "Slub Cotton",
    weaveType: "Plain Weave",
    gsm: 110,
    color: "Indigo Blue & Rust",
    unitPrice: 340,
    mrp: 580,
    stockQuantity: 200,
    unitOfMeasure: "Meters",
    reorderLevel: 40,
    supplierName: "Pink City Prints Jaipur",
    status: "In Stock",
    createdAt: "2026-03-15",
  },
  {
    id: "prod-008",
    sku: "TXT-CHI-008",
    name: "Pure Chiffon Printed Dupatta",
    category: "Dupattas & Stoles",
    fabricType: "Pure Chiffon",
    weaveType: "Plain Weave",
    gsm: 40,
    color: "Multicolor Floral",
    unitPrice: 550,
    mrp: 950,
    stockQuantity: 65,
    unitOfMeasure: "Pieces",
    reorderLevel: 20,
    supplierName: "Surat Dupatta House",
    status: "In Stock",
    createdAt: "2026-03-20",
  },
  {
    id: "prod-009",
    sku: "TXT-SHI-009",
    name: "Egyptian Giza Cotton Shirting Fabric",
    category: "Suiting & Shirting",
    fabricType: "Giza Cotton",
    weaveType: "Oxford Weave",
    gsm: 130,
    color: "Classic White",
    unitPrice: 480,
    mrp: 780,
    stockQuantity: 0,
    unitOfMeasure: "Meters",
    reorderLevel: 40,
    supplierName: "Arvind Mills",
    status: "Out of Stock",
    createdAt: "2026-04-01",
  },
  {
    id: "prod-010",
    sku: "TXT-PAT-010",
    name: "Patola Double Ikat Silk Saree",
    category: "Silk Sarees",
    fabricType: "Pure Silk",
    weaveType: "Double Ikat",
    gsm: 140,
    color: "Peacock Teal & Gold",
    unitPrice: 22000,
    mrp: 38000,
    stockQuantity: 7,
    unitOfMeasure: "Pieces",
    reorderLevel: 4,
    supplierName: "Patan Heritage Weavers",
    status: "Low Stock",
    createdAt: "2026-04-05",
  },
  {
    id: "prod-011",
    sku: "TXT-EMB-011",
    name: "Phulkari Embroidered Lawn Fabric",
    category: "Dress Material",
    fabricType: "Lawn Cotton",
    weaveType: "Embroidered",
    gsm: 80,
    color: "Bright Yellow & Pink",
    unitPrice: 720,
    mrp: 1200,
    stockQuantity: 55,
    unitOfMeasure: "Meters",
    reorderLevel: 15,
    supplierName: "Punjab Phulkari Artisans",
    status: "In Stock",
    createdAt: "2026-04-10",
  },
  {
    id: "prod-012",
    sku: "TXT-BRO-012",
    name: "Kanjivaram Silk Saree with Temple Border",
    category: "Silk Sarees",
    fabricType: "Kanjivaram Silk",
    weaveType: "Korvai Weave",
    gsm: 150,
    color: "Deep Magenta & Gold",
    unitPrice: 12500,
    mrp: 21000,
    stockQuantity: 18,
    unitOfMeasure: "Pieces",
    reorderLevel: 8,
    supplierName: "Kanchipuram Silk Weavers",
    status: "In Stock",
    createdAt: "2026-04-15",
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust-101",
    name: "Rajesh Kumar",
    businessName: "Saree Niketan Wholesale",
    phone: "+91 98250 11223",
    email: "rajesh@sareeniketan.com",
    city: "Surat",
    segment: "VIP Wholesaler",
    totalPurchasesINR: 1450000,
    totalOrdersCount: 28,
    creditLimitINR: 500000,
    outstandingBalanceINR: 120000,
    lastPurchaseDate: "2026-07-22",
  },
  {
    id: "cust-102",
    name: "Priya Sharma",
    businessName: "Couture Boutique",
    phone: "+91 98112 44556",
    email: "priya@coutureboutique.in",
    city: "Jaipur",
    segment: "Regular Retailer",
    totalPurchasesINR: 420000,
    totalOrdersCount: 14,
    creditLimitINR: 150000,
    outstandingBalanceINR: 35000,
    lastPurchaseDate: "2026-07-25",
  },
  {
    id: "cust-103",
    name: "Amit Patel",
    businessName: "Patel Matching Center",
    phone: "+91 97233 88990",
    email: "patelmatching@gmail.com",
    city: "Ahmedabad",
    segment: "Regular Retailer",
    totalPurchasesINR: 280000,
    totalOrdersCount: 9,
    creditLimitINR: 100000,
    outstandingBalanceINR: 0,
    lastPurchaseDate: "2026-07-18",
  },
  {
    id: "cust-104",
    name: "Sunita Verma",
    businessName: "Fabrics & Threads Retail",
    phone: "+91 99344 55667",
    email: "sunita.v@gmail.com",
    city: "Delhi",
    segment: "Occasional Buyer",
    totalPurchasesINR: 95000,
    totalOrdersCount: 3,
    creditLimitINR: 50000,
    outstandingBalanceINR: 12000,
    lastPurchaseDate: "2026-06-15",
  },
  {
    id: "cust-105",
    name: "Meera Nair",
    businessName: "Nair Silk Emporium",
    phone: "+91 94475 32211",
    email: "meera.nair@silkemporium.in",
    city: "Kochi",
    segment: "VIP Wholesaler",
    totalPurchasesINR: 2100000,
    totalOrdersCount: 42,
    creditLimitINR: 800000,
    outstandingBalanceINR: 250000,
    lastPurchaseDate: "2026-07-28",
  },
  {
    id: "cust-106",
    name: "Suresh Agarwal",
    businessName: "Agarwal Textile Traders",
    phone: "+91 98001 77432",
    email: "suresh@agarwaltextiles.com",
    city: "Ludhiana",
    segment: "VIP Wholesaler",
    totalPurchasesINR: 1820000,
    totalOrdersCount: 35,
    creditLimitINR: 600000,
    outstandingBalanceINR: 0,
    lastPurchaseDate: "2026-07-30",
  },
  {
    id: "cust-107",
    name: "Kavitha Reddy",
    businessName: "Reddy Fashion House",
    phone: "+91 96661 23456",
    email: "kavitha.reddy@gmail.com",
    city: "Hyderabad",
    segment: "Regular Retailer",
    totalPurchasesINR: 560000,
    totalOrdersCount: 19,
    creditLimitINR: 200000,
    outstandingBalanceINR: 48000,
    lastPurchaseDate: "2026-07-20",
  },
  {
    id: "cust-108",
    name: "Vikram Singh",
    businessName: "Singh Bridal Collections",
    phone: "+91 97890 11234",
    email: "vikram@singhbridal.in",
    city: "Chandigarh",
    segment: "Regular Retailer",
    totalPurchasesINR: 375000,
    totalOrdersCount: 12,
    creditLimitINR: 175000,
    outstandingBalanceINR: 22000,
    lastPurchaseDate: "2026-07-15",
  },
  {
    id: "cust-109",
    name: "Lakshmi Devi",
    businessName: "Devi Saree World",
    phone: "+91 93422 98765",
    email: "lakshmidevi.sarees@yahoo.in",
    city: "Chennai",
    segment: "Occasional Buyer",
    totalPurchasesINR: 68000,
    totalOrdersCount: 2,
    creditLimitINR: 40000,
    outstandingBalanceINR: 0,
    lastPurchaseDate: "2026-05-10",
  },
  {
    id: "cust-110",
    name: "Rohit Malhotra",
    businessName: "Malhotra Mens Wear",
    phone: "+91 98200 43210",
    email: "rohit.m@malhotramens.com",
    city: "Mumbai",
    segment: "Regular Retailer",
    totalPurchasesINR: 310000,
    totalOrdersCount: 11,
    creditLimitINR: 120000,
    outstandingBalanceINR: 15000,
    lastPurchaseDate: "2026-07-22",
  },
];

export const MOCK_SALES: SaleTransaction[] = [
  {
    id: "sale-901",
    invoiceNumber: "INV-2026-0789",
    customerId: "cust-101",
    customerName: "Saree Niketan Wholesale",
    items: [
      { productId: "prod-001", productName: "Pure Banarasi Zari Brocade Saree", quantity: 10, unitPrice: 8500, totalPrice: 85000 },
      { productId: "prod-003", productName: "Embroidered Georgette Anarkali Material", quantity: 15, unitPrice: 1650, totalPrice: 24750 },
    ],
    subtotalINR: 109750,
    taxINR: 5488,
    cgstINR: 2744,
    sgstINR: 2744,
    igstINR: 0,
    discountINR: 2000,
    totalINR: 113238,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Khushi Soni",
    createdAt: "2026-07-25 14:30",
  },
  {
    id: "sale-902",
    invoiceNumber: "INV-2026-0790",
    customerId: "cust-102",
    customerName: "Couture Boutique",
    items: [
      { productId: "prod-005", productName: "100% Pure Organic Linen Fabric", quantity: 40, unitPrice: 890, totalPrice: 35600 },
    ],
    subtotalINR: 35600,
    taxINR: 1780,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 1780,
    discountINR: 500,
    totalINR: 36880,
    paymentMode: "UPI",
    paymentStatus: "Paid",
    salesPerson: "Priya Soni",
    createdAt: "2026-07-26 11:15",
  },
  {
    id: "sale-903",
    invoiceNumber: "INV-2026-0791",
    customerId: "cust-103",
    customerName: "Patel Matching Center",
    items: [
      { productId: "prod-002", productName: "Chanderi Handloom Cotton Fabric", quantity: 30, unitPrice: 280, totalPrice: 8400 },
    ],
    subtotalINR: 8400,
    taxINR: 420,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 420,
    discountINR: 0,
    totalINR: 8820,
    paymentMode: "Credit Line",
    paymentStatus: "Pending",
    salesPerson: "Khushi Soni",
    createdAt: "2026-07-27 09:45",
  },
  {
    id: "sale-904",
    invoiceNumber: "INV-2026-0792",
    customerId: "cust-105",
    customerName: "Nair Silk Emporium",
    items: [
      { productId: "prod-010", productName: "Patola Double Ikat Silk Saree", quantity: 5, unitPrice: 22000, totalPrice: 110000 },
      { productId: "prod-012", productName: "Kanjivaram Silk Saree with Temple Border", quantity: 8, unitPrice: 12500, totalPrice: 100000 },
    ],
    subtotalINR: 210000,
    taxINR: 10500,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 10500,
    discountINR: 5000,
    totalINR: 215500,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Khushi Soni",
    createdAt: "2026-07-28 16:00",
  },
  {
    id: "sale-905",
    invoiceNumber: "INV-2026-0793",
    customerId: "cust-106",
    customerName: "Agarwal Textile Traders",
    items: [
      { productId: "prod-007", productName: "Jaipuri Block Print Kurti Fabric", quantity: 100, unitPrice: 340, totalPrice: 34000 },
      { productId: "prod-008", productName: "Pure Chiffon Printed Dupatta", quantity: 30, unitPrice: 550, totalPrice: 16500 },
    ],
    subtotalINR: 50500,
    taxINR: 2525,
    cgstINR: 1262,
    sgstINR: 1263,
    igstINR: 0,
    discountINR: 1000,
    totalINR: 52025,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Priya Soni",
    createdAt: "2026-07-30 10:30",
  },
  {
    id: "sale-906",
    invoiceNumber: "INV-2026-0794",
    customerId: "cust-107",
    customerName: "Reddy Fashion House",
    items: [
      { productId: "prod-003", productName: "Embroidered Georgette Anarkali Material", quantity: 20, unitPrice: 1650, totalPrice: 33000 },
      { productId: "prod-011", productName: "Phulkari Embroidered Lawn Fabric", quantity: 25, unitPrice: 720, totalPrice: 18000 },
    ],
    subtotalINR: 51000,
    taxINR: 2550,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 2550,
    discountINR: 0,
    totalINR: 53550,
    paymentMode: "UPI",
    paymentStatus: "Paid",
    salesPerson: "Khushi Soni",
    createdAt: "2026-08-01 13:00",
  },
  {
    id: "sale-907",
    invoiceNumber: "INV-2026-0795",
    customerId: "cust-108",
    customerName: "Singh Bridal Collections",
    items: [
      { productId: "prod-006", productName: "Heavy Velvet Zardozi Bridal Lehenga Fabric", quantity: 2, unitPrice: 18500, totalPrice: 37000 },
    ],
    subtotalINR: 37000,
    taxINR: 1850,
    cgstINR: 925,
    sgstINR: 925,
    igstINR: 0,
    discountINR: 500,
    totalINR: 38350,
    paymentMode: "Cash",
    paymentStatus: "Paid",
    salesPerson: "Priya Soni",
    createdAt: "2026-08-03 12:00",
  },
  {
    id: "sale-908",
    invoiceNumber: "INV-2026-0796",
    customerId: "cust-110",
    customerName: "Malhotra Mens Wear",
    items: [
      { productId: "prod-004", productName: "Super 120s Italian Wool Blend Suiting", quantity: 50, unitPrice: 620, totalPrice: 31000 },
      { productId: "prod-009", productName: "Egyptian Giza Cotton Shirting Fabric", quantity: 40, unitPrice: 480, totalPrice: 19200 },
    ],
    subtotalINR: 50200,
    taxINR: 2510,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 2510,
    discountINR: 200,
    totalINR: 52510,
    paymentMode: "Credit Line",
    paymentStatus: "Pending",
    salesPerson: "Khushi Soni",
    createdAt: "2026-08-05 15:30",
  },
  {
    id: "sale-909",
    invoiceNumber: "INV-2026-0797",
    customerId: "cust-101",
    customerName: "Saree Niketan Wholesale",
    items: [
      { productId: "prod-001", productName: "Pure Banarasi Zari Brocade Saree", quantity: 20, unitPrice: 8500, totalPrice: 170000 },
    ],
    subtotalINR: 170000,
    taxINR: 8500,
    cgstINR: 4250,
    sgstINR: 4250,
    igstINR: 0,
    discountINR: 5000,
    totalINR: 173500,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Khushi Soni",
    createdAt: "2026-08-10 09:00",
  },
  {
    id: "sale-910",
    invoiceNumber: "INV-2026-0798",
    customerId: "cust-104",
    customerName: "Fabrics & Threads Retail",
    items: [
      { productId: "prod-008", productName: "Pure Chiffon Printed Dupatta", quantity: 10, unitPrice: 550, totalPrice: 5500 },
      { productId: "prod-011", productName: "Phulkari Embroidered Lawn Fabric", quantity: 8, unitPrice: 720, totalPrice: 5760 },
    ],
    subtotalINR: 11260,
    taxINR: 563,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 563,
    discountINR: 0,
    totalINR: 11823,
    paymentMode: "UPI",
    paymentStatus: "Pending",
    salesPerson: "Priya Soni",
    createdAt: "2026-08-12 11:00",
  },
  {
    id: "sale-911",
    invoiceNumber: "INV-2026-0799",
    customerId: "cust-106",
    customerName: "Agarwal Textile Traders",
    items: [
      { productId: "prod-005", productName: "100% Pure Organic Linen Fabric", quantity: 80, unitPrice: 890, totalPrice: 71200 },
      { productId: "prod-002", productName: "Chanderi Handloom Cotton Fabric", quantity: 60, unitPrice: 280, totalPrice: 16800 },
    ],
    subtotalINR: 88000,
    taxINR: 4400,
    cgstINR: 2200,
    sgstINR: 2200,
    igstINR: 0,
    discountINR: 2000,
    totalINR: 90400,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Khushi Soni",
    createdAt: "2026-08-15 14:00",
  },
  {
    id: "sale-912",
    invoiceNumber: "INV-2026-0800",
    customerId: "cust-105",
    customerName: "Nair Silk Emporium",
    items: [
      { productId: "prod-012", productName: "Kanjivaram Silk Saree with Temple Border", quantity: 10, unitPrice: 12500, totalPrice: 125000 },
    ],
    subtotalINR: 125000,
    taxINR: 6250,
    cgstINR: 0,
    sgstINR: 0,
    igstINR: 6250,
    discountINR: 3000,
    totalINR: 128250,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Priya Soni",
    createdAt: "2026-08-18 10:00",
  },
];

export const MOCK_AI_OVERVIEW: AIPredictionOverview = {
  predictedNextMonthSalesINR: 1850000,
  growthPercentage: 14.2,
  highDemandCategory: "Silk Sarees",
  predictedDeadStockItemsCount: 4,
  recommendedRestockCount: 6,
};

export const MOCK_SALES_FORECAST: SalesForecastPoint[] = [
  { month: "Feb", actualSalesINR: 1200000, predictedSalesINR: 1180000 },
  { month: "Mar", actualSalesINR: 1350000, predictedSalesINR: 1320000 },
  { month: "Apr", actualSalesINR: 1410000, predictedSalesINR: 1450000 },
  { month: "May", actualSalesINR: 1580000, predictedSalesINR: 1520000 },
  { month: "Jun", actualSalesINR: 1620000, predictedSalesINR: 1640000 },
  { month: "Jul", actualSalesINR: 1710000, predictedSalesINR: 1700000 },
  { month: "Aug (Pred)", actualSalesINR: 0, predictedSalesINR: 1850000 },
  { month: "Sep (Pred)", actualSalesINR: 0, predictedSalesINR: 2100000 },
];

export const MOCK_DEMAND_ITEMS: DemandForecastItem[] = [
  {
    productId: "prod-001",
    productName: "Pure Banarasi Zari Brocade Saree",
    category: "Silk Sarees",
    currentStock: 45,
    predictedDemandNext30Days: 95,
    recommendedAction: "Restock Immediately",
    confidenceScore: 94,
  },
  {
    productId: "prod-002",
    productName: "Chanderi Handloom Cotton Fabric",
    category: "Cotton Fabrics",
    currentStock: 12,
    predictedDemandNext30Days: 140,
    recommendedAction: "Restock Immediately",
    confidenceScore: 91,
  },
  {
    productId: "prod-005",
    productName: "100% Pure Organic Linen Fabric",
    category: "Linen Collection",
    currentStock: 120,
    predictedDemandNext30Days: 110,
    recommendedAction: "Maintain Stock",
    confidenceScore: 88,
  },
];

export const MOCK_BUNDLE_RECOMMENDATIONS: BundleRecommendation[] = [
  {
    id: "mock-bundle-1",
    items: ["Banarasi Silk Saree", "Zardozi Dupatta"],
    description: "84% of wholesale buyers purchasing Banarasi Sarees also order matching Dupattas.",
    confidence: 0.84,
    lift: 2.1,
  },
  {
    id: "mock-bundle-2",
    items: ["Cotton Kurti Fabric", "Linen Trouser Material"],
    description: "65% of customers buying Kurti fabric pair it with Linen trouser material.",
    confidence: 0.65,
    lift: 1.8,
  },
];
