import {
  Product,
  Customer,
  SaleTransaction,
  AIPredictionOverview,
  SalesForecastPoint,
  DemandForecastItem,
  BundleRecommendation,
} from "../types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    sku: "TXT-SILK-001",
    name: "Pure Banarasi Zari Brocade Saree",
    category: "Silk Sarees",
    fabricType: "Katan Silk",
    weaveType: "Jacquard Weave",
    gsm: 120,
    color: "Royal Crimson Red",
    unitPrice: 8500,
    mrp: 14500,
    stockQuantity: 45,
    unitOfMeasure: "Pieces",
    reorderLevel: 15,
    supplierName: "Varanasi Heritage Weavers",
    status: "In Stock",
    createdAt: "2026-01-10",
  },
  {
    id: "prod-002",
    sku: "TXT-COT-002",
    name: "Chanderi Handloom Cotton Fabric",
    category: "Cotton Fabrics",
    fabricType: "Chanderi Cotton",
    weaveType: "Plain Weave",
    gsm: 75,
    color: "Pastel Mint Green",
    unitPrice: 280,
    mrp: 450,
    stockQuantity: 12,
    unitOfMeasure: "Meters",
    reorderLevel: 50,
    supplierName: "Chanderi Craft Co-op",
    status: "Low Stock",
    createdAt: "2026-02-01",
  },
  {
    id: "prod-003",
    sku: "TXT-DRS-003",
    name: "Embroidered Georgette Anarkali Material",
    category: "Dress Material",
    fabricType: "Faux Georgette",
    weaveType: "Chiffon Weave",
    gsm: 90,
    color: "Deep Sapphire Blue",
    unitPrice: 1650,
    mrp: 2890,
    stockQuantity: 85,
    unitOfMeasure: "Pieces",
    reorderLevel: 20,
    supplierName: "Surat Tex Fabrics",
    status: "In Stock",
    createdAt: "2026-01-25",
  },
  {
    id: "prod-004",
    sku: "TXT-SUIT-004",
    name: "Super 120s Italian Wool Blend Suiting",
    category: "Suiting & Shirting",
    fabricType: "Wool Rayon Blend",
    weaveType: "Twill Weave",
    gsm: 240,
    color: "Charcoal Grey",
    unitPrice: 620,
    mrp: 990,
    stockQuantity: 8,
    unitOfMeasure: "Meters",
    reorderLevel: 30,
    supplierName: "Raymond Mills Distributor",
    status: "Low Stock",
    createdAt: "2026-02-14",
  },
  {
    id: "prod-005",
    sku: "TXT-LIN-005",
    name: "100% Pure Organic Linen Fabric",
    category: "Linen Collection",
    fabricType: "Flax Linen",
    weaveType: "Basket Weave",
    gsm: 160,
    color: "Natural Ecru Beige",
    unitPrice: 890,
    mrp: 1400,
    stockQuantity: 120,
    unitOfMeasure: "Meters",
    reorderLevel: 25,
    supplierName: "Bhagalpur Linen Mills",
    status: "In Stock",
    createdAt: "2026-03-02",
  },
  {
    id: "prod-006",
    sku: "TXT-LEH-006",
    name: "Heavy Velvet Zardozi Bridal Lehenga Fabric",
    category: "Designer Lehengas",
    fabricType: "Micro Velvet 9000",
    weaveType: "Velvet Cut Weave",
    gsm: 310,
    color: "Maroon Rose",
    unitPrice: 18500,
    mrp: 29900,
    stockQuantity: 3,
    unitOfMeasure: "Pieces",
    reorderLevel: 5,
    supplierName: "Jaipur Artisan Guild",
    status: "Low Stock",
    createdAt: "2026-03-10",
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust-101",
    name: "Rajesh Kumar",
    businessName: "Saree Niketan Wholesale",
    phone: "+91 98250 11223",
    email: "rajesh@sareeniketan.com",
    city: "Surat",
    segment: "VIP Wholesaler",
    totalPurchasesINR: 1450000,
    totalOrdersCount: 28,
    creditLimitINR: 500000,
    outstandingBalanceINR: 120000,
    lastPurchaseDate: "2026-07-22",
  },
  {
    id: "cust-102",
    name: "Priya Sharma",
    businessName: "Couture Boutique",
    phone: "+91 98112 44556",
    email: "priya@coutureboutique.in",
    city: "Jaipur",
    segment: "Regular Retailer",
    totalPurchasesINR: 420000,
    totalOrdersCount: 14,
    creditLimitINR: 150000,
    outstandingBalanceINR: 35000,
    lastPurchaseDate: "2026-07-25",
  },
  {
    id: "cust-103",
    name: "Amit Patel",
    businessName: "Patel Matching Center",
    phone: "+91 97233 88990",
    email: "patelmatching@gmail.com",
    city: "Ahmedabad",
    segment: "Regular Retailer",
    totalPurchasesINR: 280000,
    totalOrdersCount: 9,
    creditLimitINR: 100000,
    outstandingBalanceINR: 0,
    lastPurchaseDate: "2026-07-18",
  },
  {
    id: "cust-104",
    name: "Sunita Verma",
    businessName: "Fabrics & Threads Retail",
    phone: "+91 99344 55667",
    email: "sunita.v@gmail.com",
    city: "Delhi",
    segment: "Occasional Buyer",
    totalPurchasesINR: 95000,
    totalOrdersCount: 3,
    creditLimitINR: 50000,
    outstandingBalanceINR: 12000,
    lastPurchaseDate: "2026-06-15",
  },
];

export const MOCK_SALES: SaleTransaction[] = [
  {
    id: "sale-901",
    invoiceNumber: "INV-2026-0789",
    customerId: "cust-101",
    customerName: "Saree Niketan Wholesale",
    items: [
      {
        productId: "prod-001",
        productName: "Pure Banarasi Zari Brocade Saree",
        quantity: 10,
        unitPrice: 8500,
        totalPrice: 85000,
      },
      {
        productId: "prod-003",
        productName: "Embroidered Georgette Anarkali Material",
        quantity: 15,
        unitPrice: 1650,
        totalPrice: 24750,
      },
    ],
    subtotalINR: 109750,
    taxINR: 5488, // 5% GST on Textiles
    discountINR: 2000,
    totalINR: 113238,
    paymentMode: "Bank Transfer",
    paymentStatus: "Paid",
    salesPerson: "Khushi Soni (Owner)",
    createdAt: "2026-07-25 14:30",
  },
  {
    id: "sale-902",
    invoiceNumber: "INV-2026-0790",
    customerId: "cust-102",
    customerName: "Couture Boutique",
    items: [
      {
        productId: "prod-005",
        productName: "100% Pure Organic Linen Fabric",
        quantity: 40,
        unitPrice: 890,
        totalPrice: 35600,
      },
    ],
    subtotalINR: 35600,
    taxINR: 1780,
    discountINR: 500,
    totalINR: 36880,
    paymentMode: "UPI",
    paymentStatus: "Paid",
    salesPerson: "Kavita Shah (Employee)",
    createdAt: "2026-07-26 11:15",
  },
  {
    id: "sale-903",
    invoiceNumber: "INV-2026-0791",
    customerId: "cust-103",
    customerName: "Patel Matching Center",
    items: [
      {
        productId: "prod-002",
        productName: "Chanderi Handloom Cotton Fabric",
        quantity: 30,
        unitPrice: 280,
        totalPrice: 8400,
      },
    ],
    subtotalINR: 8400,
    taxINR: 420,
    discountINR: 0,
    totalINR: 8820,
    paymentMode: "Credit Line",
    paymentStatus: "Pending",
    salesPerson: "Khushi Soni (Owner)",
    createdAt: "2026-07-27 09:45",
  },
];

export const MOCK_AI_OVERVIEW: AIPredictionOverview = {
  predictedNextMonthSalesINR: 1850000,
  growthPercentage: 14.2,
  highDemandCategory: "Silk Sarees",
  predictedDeadStockItemsCount: 4,
  recommendedRestockCount: 6,
};

export const MOCK_SALES_FORECAST: SalesForecastPoint[] = [
  { month: "Feb", actualSalesINR: 1200000, predictedSalesINR: 1180000 },
  { month: "Mar", actualSalesINR: 1350000, predictedSalesINR: 1320000 },
  { month: "Apr", actualSalesINR: 1410000, predictedSalesINR: 1450000 },
  { month: "May", actualSalesINR: 1580000, predictedSalesINR: 1520000 },
  { month: "Jun", actualSalesINR: 1620000, predictedSalesINR: 1640000 },
  { month: "Jul", actualSalesINR: 1710000, predictedSalesINR: 1700000 },
  { month: "Aug (Pred)", actualSalesINR: 0, predictedSalesINR: 1850000 },
  { month: "Sep (Pred)", actualSalesINR: 0, predictedSalesINR: 2100000 },
];

export const MOCK_DEMAND_ITEMS: DemandForecastItem[] = [
  {
    productId: "prod-001",
    productName: "Pure Banarasi Zari Brocade Saree",
    category: "Silk Sarees",
    currentStock: 45,
    predictedDemandNext30Days: 95,
    recommendedAction: "Restock Immediately",
    confidenceScore: 94,
  },
  {
    productId: "prod-002",
    productName: "Chanderi Handloom Cotton Fabric",
    category: "Cotton Fabrics",
    currentStock: 12,
    predictedDemandNext30Days: 140,
    recommendedAction: "Restock Immediately",
    confidenceScore: 91,
  },
  {
    productId: "prod-005",
    productName: "100% Pure Organic Linen Fabric",
    category: "Linen Collection",
    currentStock: 120,
    predictedDemandNext30Days: 110,
    recommendedAction: "Maintain Stock",
    confidenceScore: 88,
  },
];

export const MOCK_BUNDLE_RECOMMENDATIONS: BundleRecommendation[] = [
  {
    id: "mock-bundle-1",
    items: ["Banarasi Silk Saree", "Zardozi Dupatta"],
    description: "84% of wholesale buyers purchasing Banarasi Sarees also order matching Dupattas.",
    confidence: 0.84,
    lift: 2.1,
  },
  {
    id: "mock-bundle-2",
    items: ["Cotton Kurti Fabric", "Linen Trouser Material"],
    description: "65% of customers buying Kurti fabric pair it with Linen trouser material.",
    confidence: 0.65,
    lift: 1.8,
  },
];
